serverdensity/sd-agent

install.sh

Adds tagging ability into the installer
Usage: sd-install.sh -a account -t token -T newtag
- Retrieves all existing tags using the API
- Using sed/grep to see if the tag exists
- If it does, stores the ID in TAGID
- If it doesn't, creates the tag and stores the ID in TAGID using a random hex code (echo tagname | md5 | cut -c1-6)

Installer tags

---

checks.py

This should fix the bug when we extract the wrong volume name from GCE machines if they have a '-' char in its name.
Without this patch, if we find:
/dev/disk/by-id/google-cpm-test
the volumeName would be extracted as 'cpm' instead of 'cpm-test'

We are just interested on remove the 'google-' prefix from the diskName

---

install.sh

In our infrastructure, we are based on CoreOS.
To be able to run additional tools, CoreOS provide a shell "/bin/toolbox" which use a fedora docker image mapped directly inside the host.
My purpose is to auto-deploy and start the Server Density Agent, based on a global fleetd unit file.
To do so, i had to add Fedora 21 in the supported platform in the script install.sh.

Add the support of Fedora release 21

---

checks/collector.py

If the gohai command raises an exception then simply log it as
informational rather than throw an exception or log as an error.
This means we can close SD-2129.
@carlosperello can you review please?

Relax gohai exception

---

utils/pip-allow-failures.sh

Updated shebang to make pip-allow-failures.sh script portable.
@carlosperello can you review please?

- Update shebang

---

agent.py
checks.d/sd.py
checks.d/sd_cpu_stats.py
checks/system/unix.py

It adapts the agent's source to run properly on Mac OS X systems (aka Darwin) taking into account its idiosyncrasies.
The commits are small and pretty much self-explanatory. They're also properly isolated from other's systems branches (except for the shebang change, which should work on any system)
Install the agent from source and run it, check that the metrics reported are correct, as opposed to before the changes
Most of the differences lay in the system utilities, which accept different arguments or produce other output by default.
There's also a pending ticket referring to the way CPU stats are reported. No default system utility in OS X reports CPU activity per CPU. This needs to be fixed with a custom utility, or changing the UI (and mobile clients) requests metrics for darwin …

SD-2316 Update darwin support

---

.travis.yml
config.py
debian/changelog
debian/control
debian/sd-agent-hdfs.install
packaging/darwin/build_installer.sh
packaging/darwin/darwin_version.sh
packaging/darwin/distribution.xml
packaging/el/SPECS/sd-agent-el6.spec
packaging/el/SPECS/sd-agent-el7.spec
packaging/el/inc/changelog
packaging/el/inc/install
packaging/el/inc/install.el5
packaging/el/inc/subpackages
packaging/el/inc/version
requirements-opt.txt
utils/configcheck.py

- Adds HDFS plugins official support.
- docker_daemon plugin fixed on .RPM packages
- pycurl fixes to use the agent as a proxy of other agents.

Release 2.1.4

---

packaging/source/agent

This PR allows agent source installs to be stopped by fixing the socket file location and by killing the leftover supervisord process id once all child processes have been stopped. 
Can be tested by installing a source install: 
`curl https://archive.serverdensity.com/agent-install-source.sh | sudo bash -s -- -a test -k testkey` (You don't need a valid account and key to test this)
Then start with `bin/agent start`
See that the agent starts, then attempt to stop with `bin/agent stop` 
and see that fails with `Supervisor is not running`. 
(Can also verify supervisord process is still running with `ps aux | grep sd-agent` or `ps aux | grep py`) 
Drop in the replacement from this branch and then attempt to `bin/agent stop` and see that you get
```
sd-agent:forwarder: stopped …
```

Stop source install

---

debian/distros/trusty/sd-agent.init
packaging/el/sd-agent-pkg.init

This PR ensures that `su $AGENTUSER -c "$SDSTATSDPATH info"` is only executed if the `$SDSTATSDPATH` path exists. 
As we don't ship sdstatsd with the core agent and `$SDSTATSDPATH` is not defined in the init.d file the current init.d file executes `su $AGENTUSER -c " info"` which is incorrect and confusing. 
This PR fixes this and restores expected behaviour.
@serverdensity/backend-engineering please can someone review?

Check if sdstatsdpath exists before executing info

---

checks/system/unix.py
utils/subprocess_output.py

This PR ensures that the C locale is used for the io check, ensuring that all users can collect disk io metrics regardless of what their locale is set to. 
@sixstone-qq or @carlosperello please can you review?

use C locale for iostat subprocess env

---

checks/collector.py

This PR disables the gohai error unless debug mode is enabled. 
@carlosperello please can you review and merge if happy?

Only log gohai error in debug

---

utils/dockerutil.py

This PR prevents the orcherstator warning from being shown unless the agent is in debug mode. 
@carlosperello please can you review?

Log orchestrator error in debug only

---

.travis.yml
config.py
debian/changelog
packaging/darwin/darwin_version.sh
packaging/el/inc/changelog
packaging/el/inc/version

This PR updates the files that contain the version number and changelogs for the next agent release.
To be merged after #153, #154 & #156
https://github.com/serverdensity/sd-agent-core-plugins/pull/12  and  https://github.com/serverdensity/sd-agent-core-plugins/pull/15 are also required too.

Version bump

---

tests/core/test_common.py

This PR fixes the currently broken test on Travis. 
Travis appears to be adding a proxy named `travis_apt` which causes the test to fail as it is not in the expected proxies list. This appears to be a recent change (altho I can't find anything in the Travis docs about it).
Tests are passing on this branch on Travis . 
@carlosperello please can you review?

Fix proxy tests

---

requirements.txt

This PR increases the required pyyaml version to 4.2b1 to mitigate CVE-2017-18342.

Bump pyyaml to >=4.2b1

---

emitter.py

This PR enables compression of the payloads before they are sent back to SD for processing. 
The backend changes for this have been deployed for 24hrs+ along with a test build of the agent and there does not appear to be any issues.

Enable payload compression

---

debian/distros/bionic/sd-agent-forwarder.service
debian/distros/bionic/sd-agent-jmx.service
debian/distros/bionic/sd-agent-sdstatsd.service
debian/distros/bionic/sd-agent.service
debian/distros/stretch/sd-agent-forwarder.service
debian/distros/stretch/sd-agent-jmx.service
debian/distros/stretch/sd-agent-sdstatsd.service
debian/distros/stretch/sd-agent.service
debian/distros/xenial/sd-agent-forwarder.service
debian/distros/xenial/sd-agent-jmx.service
debian/distros/xenial/sd-agent-sdstatsd.service
debian/distros/xenial/sd-agent.service
debian/sd-agent-forwarder.service
debian/sd-agent-jmx.service
debian/sd-agent-sdstatsd.service
debian/sd-agent.service

This PR updates the service files that are shipped with the agent on systemd enabled servers to prevent the service from automatically logging to syslog, despite disabling syslogging in the agent config. 
Raised in #169 . 
Packages have been tested and logs are not pushed to syslog when the agent is configured not to. 
@NassimHC please can you review/merge?

Redirect systemd logs to null

---

debian/control
debian/distros/bionic/control
debian/distros/stretch/control
debian/distros/trusty/control
debian/distros/xenial/control

This PR updates the packaging metadata to ensure that sd-agent-forwarder is uninstalled when sd-agent is uninstalled. 
Packages have been tested. 
@NassimHC please can you review/merge?

Uninstall sd-agent-forwarder on sd-agent uninstall

---

.travis/dockerfiles/jessie/Dockerfile
.travis/dockerfiles/jessie/entrypoint.sh
.travis/dockerfiles/stretch/entrypoint.sh
.travis/dockerfiles/trusty/entrypoint.sh
.travis/dockerfiles/xenial/entrypoint.sh

Builds have been failing for the past week as `jessie-updates/` has been removed from the Debian mirrors. This prevents the chroot from being created which causes the build to fail.
This PR adds `--other-mirrors` config to the the jessie build working around this issue. 
This also adds a chroot update to all of the debian/ubuntu OS builds so that old chroot envs don't break builds.
@NassimHC please can you review and merge if happy?

Fix jessie builds

---

.travis/dockerfiles/el6_i386/Dockerfile
.travis/dockerfiles/jessie/Dockerfile

Jessie builds started failing again, adding the `--mirror` to the pbuilder-dist command resolves this. 
Whilst working on this the el6_i386 builds started failing too. The base image is old and doesn't get any updates. Adding `yum update -y` to the dockerfile resolved the issue.
@NassimHC please can you review and merge if happy?

Fix jessie build

---

.travis/dockerfiles/el6_i386/Dockerfile
.travis/dockerfiles/el6_i386/entrypoint.sh

This PR fixes the el_i386 builds by switching to the archive repo for ius as python27 is no longer available in the main repo.
Builds are completing successfully with this change and as this change only impacts the docker containers for builds this does not need any further testing. 
However, @NassimHC please can you review and merge if happy?

Build fix el6 i386

---

.travis/dockerfiles/bionic/Dockerfile
.travis/dockerfiles/bionic/entrypoint.sh
.travis/dockerfiles/buster/Dockerfile
.travis/dockerfiles/buster/entrypoint.sh
.travis/dockerfiles/stretch/Dockerfile
.travis/dockerfiles/stretch/entrypoint.sh
.travis/dockerfiles/trusty/Dockerfile
.travis/dockerfiles/trusty/entrypoint.sh
.travis/dockerfiles/xenial/Dockerfile
.travis/dockerfiles/xenial/entrypoint.sh

Enables builds for arm64 arch type on Debian and Ubuntu OS's. 
Debian Jessie was skipped as it is EoL June 30th 2020.

Enable arm builds for Debian & Ubuntu

---

.travis.yml

On the previous PR I didn't anticipate any issues with OS X, however it unintentionally broke the OS X builds with the rvm install command. 
This PR fixes that issue and allows OS X builds to complete successfully. 
@NassimHC please review :)

Fix Travis CI OS X Build

---

requirements.txt

This PR bumps the ntplib version pin to 0.3.4 as 0.3.3 was removed from pypi. 
A version bump is required as we have updated deps, but this will come in a later PR which brings focal builds.
@NassimHC please review and merge if happy

bump ntplib - 0.3.4

---

packaging/source/freebsd-agent

Add rc.d file for easy user configuration on FreeBSD. Instead of copy/pasting a configuration, they can curl the file.

Add rc.d file for easy user configuration

---

.travis/dockerfiles/el6/Dockerfile
.travis/dockerfiles/el6_i386/Dockerfile

Updates the ius-release URLs that are used in the build containers as the redirects no longer work. 
Builds are passing with this change.
@NassimHC please review and merge if happy.

Update ius-release URLs for Travis Builds

---

debian/rules
packaging/el/SPECS/sd-agent-el6.spec
packaging/el/SPECS/sd-agent-el7.spec
packaging/el/SPECS/sd-agent-el8.spec

This PR bumps setuptools to v44.1.1 so that the builds match between sd-agent and sd-agent-core plugins. 
Setuptools is not shipped with the agent, so this does not need a version bump and release as this impacts builds only. 
@NassimHC please review.

Bump setuptools to 44.1.1

---

.travis.yml
.travis/dockerfiles/bionic/entrypoint.sh
.travis/dockerfiles/buster/entrypoint.sh
.travis/dockerfiles/el8/Dockerfile
.travis/dockerfiles/focal/entrypoint.sh
.travis/dockerfiles/stretch/entrypoint.sh
.travis/dockerfiles/trusty/entrypoint.sh
.travis/dockerfiles/xenial/entrypoint.sh
README.md
Rakefile
debian/distros/bionic/rules
debian/distros/buster/rules
debian/distros/focal/rules
debian/distros/stretch/rules
debian/distros/trusty/rules
debian/distros/xenial/rules
debian/rules
packaging/darwin/build_installer.sh
packaging/el/SPECS/sd-agent-el6.spec
packaging/el/SPECS/sd-agent-el7.spec
packaging/el/SPECS/sd-agent-el8.spec

This PR: 
* Fixes get-pip URL for 2.7.
* Updates el8 powertools repository name.
* Pins pip to <19.
* Removes el6 from travis config, but has not removed the files.
* Ensures dpkg-source is executed after the control file is updated for the specific ubuntu/debian release.
* Removes an extra / from the PACKAGES_DIR path in MacOS builds ensuring build artifacts are uploaded to GCS.
* Updates travis-ci badge to .com, as the repository has been migrated.
Builds are successful on this branch and the agent has been tested to ensure that this did not inadvertently break any functionality

Build Fixes

---

.travis.yml
.travis/dockerfiles/focal/Dockerfile
.travis/dockerfiles/focal/entrypoint.sh

This PR updates the build scripts to enable aarch64/arm64 builds for Ubuntu Focal per customer requests. 
A couple of things to note: 
* The Focal container build and package build stages now run on a Focal host 
* The error `semop(1): encountered an error: Function not implemented` was seen when running the builds and prevented them from completing. To workaround this the `ppa:canonical-server/server-backports`  is added to Focal hosts which allows qemu-user-static backported from Groovy to be installed which resolves this error. [0]
* We were previously using ruby 2.1.5, however Focal does not have the correct dependencies available for this, so I bumped the Ruby version to 2.5 for everything instead of working around the dependency issue with 2.1.5 and Focal.
* This bump was completed …

Enable Focal aarch64/arm64 builds 

---

.travis.yml
.travis/dockerfiles/bullseye/Dockerfile
.travis/dockerfiles/buster/Dockerfile
config.py
debian/changelog
debian/distros/bionic/rules
debian/distros/bullseye/rules
debian/distros/buster/rules
debian/distros/focal/rules
debian/distros/stretch/rules
debian/distros/trusty/rules
debian/distros/xenial/rules
debian/rules
packaging/darwin/darwin_version.sh
packaging/el/inc/changelog
packaging/el/inc/download_jmx_fetch
packaging/el/inc/version

* Bumps jmxfetch to 0.44.4 to mitigate CVE-2021-44228
* Bumps sd-agent version number to 2.2.9
* Minor build fixes for bullseye and buster. Builds are completed on 18.04 containers but this does not have the latest debian-archive-keyring in the repository preventing debootstrap from installing required packages. Updated the Dockerfiles to download and install the latest debian-archive-keyring as I hit kernel issues when bumping the ubuntu images to latest than 18.04. 
@pessoa please can you review?

Bump Jmxfetch Version

---

config.py
debian/changelog
debian/distros/bionic/rules
debian/distros/bullseye/rules
debian/distros/buster/rules
debian/distros/focal/rules
debian/distros/stretch/rules
debian/distros/trusty/rules
debian/distros/xenial/rules
debian/rules
packaging/el/inc/changelog
packaging/el/inc/download_jmx_fetch
requirements-test.txt

* Bumps JMXFetch version to 0.44.5 to mitigate CVE-2021-45046 and CVE-2021-44228
* Pins lazy-object-proxy==1.6.0 to ensure test requirements can be installed. 
Agent version did not get bump as we have not released it yet.
@pessoa please can I have a review?

Bump JMXFetch Version - 0.44.5

---

packaging/el/inc/files

* Updates the el packaging to only ship the required libs, in practice this means that jmxfetch.jar is only shipped in sd-agent-jmx and not the sd-agent package.
@pessoa please can you review?

Update EL packaging

---

config.py
debian/distros/bionic/rules
debian/distros/bullseye/rules
debian/distros/buster/rules
debian/distros/focal/rules
debian/distros/stretch/rules
debian/distros/trusty/rules
debian/distros/xenial/rules
debian/rules
packaging/el/inc/download_jmx_fetch

This PR:
* Bumps JMXFetch to 0.44.6 which removes log4j entirely.
The builds will fail until #201 is merged as #201 contains a fix for the el8 build container.

Bump jmxfetch to 0.44.6

---

.travis.yml
.travis/dockerfiles/el7_arm/Dockerfile
.travis/dockerfiles/el7_arm/entrypoint.sh
.travis/dockerfiles/el8/Dockerfile
.travis/dockerfiles/el8_arm/Dockerfile
.travis/dockerfiles/el8_arm/entrypoint.sh
packaging/el/SPECS/sd-agent-el7.spec
packaging/el/SPECS/sd-agent-el8.spec

This PR: 
* Fixes an error in the el8 build containers.
* Adds packaging for aarch64 for el7/8
* Removes the BuildArch from the el SPEC files as the build arch is implied from the build container's arch. 
* Adds travis_wait to all script commands as the el containers do not output anything for over 10mins (causing the build to be deemed failed) despite still running.

Add El ARM Packaging 

---

.travis.yml

This PR removes Jessie builds from the Travis config.
Jessie is EoL for years and the builds are now failing. We have old builds and will preserve an old version of the agent for Jessie in the repos, per other EoL OS.
@pessoa to review.

Remove Jessie Builds

---

requirements.txt

This PR pins urllib3==1.24.3. 
This is required as the http-check makes use of requests and urllib3, but the dependency for requests is specified in the core agent. 
python-etcd was pulling in urllib3-1.26.8 which is not compatible with the current requests version.  urllib3==1.24.3 satisfies the requirements of both requests and python-etcd and ensures that the http-check will function without user intervention. 
Also a minor fix in the travis yml to ensure csvlint runs. 
@pessoa to review

Pin urllib3==1.24.3

---

.travis.yml
config.py
debian/changelog
packaging/darwin/darwin_version.sh
packaging/el/inc/changelog
packaging/el/inc/version

This PR bumps the packaging version to 2.6.7, ready for release.
Ideally this should be merged last, after #207 & #208
@pessoa to review

Bump agent version to 2.2.11
