serverdensity/sd-agent

install.sh

Prompted by a customer to add CL support

Add CloudLinux support

---

checks.py

New key partition can contain the following values:
* 0 - Everything is fine
* 1 - Partition detected
Afaik the only way to monitor the health of a RabbitMQ cluster from the HTTP API.
Cheers :beers:
Daniel

Monitor rabbitmq cluster partitions

---

checks.py

Fixes an issue in Mac OS when the number of spaces is not the expected one
checks.py
Make sure that the modified method works well with the different possible input values
None
- @bassdread or @carlosperello (review)
See case SD-1003

Fix for issue reported in SD-1003

---

install.sh

forgot while doing:
https://github.com/serverdensity/sd-agent/commit/384e959671608eae83a4298c19191b29de399647

allow curl to follow redirects

---

agent.py
checks.py
config.cfg

Adds queue name filtering to rabbitmq
checks.py
Configure a rabbitmq server to work with the agent and make sure the regex filtering works
None
- @bassdread or @carlosperello  (review)

Rabbitmq queue filtering

---

checks.py

Adds queue field name filtering to rabbitmq
checks.py
Run it and make sure all the relevant fields are still received by the postback endpoint
None
- @bassdread or @carlosperello  (review)

Add rabbitmq queue fields filtering

---

config.py
debian/changelog
packaging/el/inc/changelog
packaging/el/inc/version

Release 2.0.5

---

config.py
debian/changelog
packaging/el/inc/changelog
packaging/el/inc/version

Reverts serverdensity/sd-agent#123

Revert "Release 2.0.5"

---

config.py
debian/changelog
packaging/el/inc/changelog
packaging/el/inc/version

Revert "Revert "Release 2.0.5""

---

packaging/source/agent
packaging/source/supervisor.conf

- Added a packaging/source directory for use with source installs.
- Added a portable supervisor.conf to the dir.
- Added init script to the dir.
This, along with #119, will resolve SD-2192
@serverdensity/backend-engineering could someone review please?

Add needed files

---

checks.d/directory.py
checks.d/docker.py
checks.d/postfix.py
checks/system/unix.py
config.py
sdagent.py
win32/agent.py

Fixed branding issue. 
Port incremented. 
@harryperks @carlosperello

SD-2813/Port Change

---

checks.d/sd_cpu_stats.py
checks/system/unix.py
ci/default.rb
packaging/darwin/build_installer.sh
requirements-test.txt

Set of changes required to get macOS build fixed and FreeBSD reporting the right core stats.

Release 2.1.0

---

.travis.yml
config.py
debian/changelog
debian/control
debian/sd-agent.init
packaging/darwin/darwin_version.sh
packaging/darwin/distribution.xml
packaging/el/inc/changelog
packaging/el/inc/subpackages
packaging/el/inc/version
packaging/el/sd-agent-pkg.init
utils/dockerutil.py

Fixed a critical issue on our packages that break the agent restart after a server reboot.

Release 2.1.1

---

.travis.yml
config.py
debian/changelog
debian/control
debian/sd-agent-haproxy.install
packaging/darwin/build_installer.sh
packaging/darwin/darwin_version.sh
packaging/darwin/distribution.xml
packaging/el/inc/changelog
packaging/el/inc/install
packaging/el/inc/install.el5
packaging/el/inc/subpackages
packaging/el/inc/version

This is a 2.1.2 release which includes the activation of the haproxy plugin.

Release 2.1.2

---

.travis.yml
checks.d/elastic.py
conf.d/elastic.yaml.example
config.py
debian/changelog
debian/control
debian/sd-agent-elastic.install
packaging/darwin/build_installer.sh
packaging/darwin/darwin_version.sh
packaging/darwin/distribution.xml
packaging/el/inc/changelog
packaging/el/inc/install
packaging/el/inc/install.el5
packaging/el/inc/subpackages
packaging/el/inc/version
tests/checks/integration/test_elastic.py

2.1.3 update.
- Fixes Enterprise Linux packaging for HAProxy.
- Includes the Elastic Search plugin.

Release 2.1.3

---

.travis.yml
conf.d/couchbase.yaml.example
config.py
debian/changelog
debian/control
packaging/darwin/build_installer.sh
packaging/darwin/darwin_version.sh
packaging/darwin/distribution.xml
packaging/el/inc/changelog
packaging/el/inc/install
packaging/el/inc/install.el5
packaging/el/inc/subpackages
packaging/el/inc/version

Release 2.1.5 including couchbase plugin

Release 2.1.5

---

checks/system/unix.py

Newer iostat versions also expose slightly different fields. This PR adds support for iostat in bionic. 
@carlosperello please can you review?

[IO] Fix for newer iostat output format

---

.travis/dockerfiles/el6_i386/Dockerfile

Fixes build issues with the el6_i386 container and the ius repository. 
@NassimHC please can you review and merge if happy. The build has completed successfully with these changes.

Update ius repo location

---

.travis/dockerfiles/el8/Dockerfile

Resolves a small issue with building the el8 container where unzip would fail to install, this also has the benefit of matching the sd-agent-core-plugins Dockerfile.
@NassimHC please can you review and merge?

Update el8 Dockerfile

---

.travis.yml
tests/core/test_proxy.py

This fixes up the .travis.yaml errors which were preventing builds from running properly. 
I also had to disable a proxy test as the setup for it is not completing properly causing the test to fail and I was unable to determine the cause. 
@NassimHC please can you review?

Fix Travis CI errors

---

.travis/dockerfiles/el6/Dockerfile
.travis/dockerfiles/el6_i386/Dockerfile

Updates the el6 containers to match the install instructions.

Update el6 containers to use ius-archive

---

.travis.yml

Removes trusty from the Travis builds.

Remove trusty builds

---

.travis.yml
config.py
debian/changelog
packaging/darwin/darwin_version.sh
packaging/el/inc/changelog
packaging/el/inc/version

* Updates the agent config and change logs to v2.2.10

Version 2.2.10

---

debian/distros/bionic/rules
debian/distros/bullseye/rules
debian/distros/buster/rules
debian/distros/focal/rules
debian/distros/stretch/rules
debian/distros/trusty/rules
debian/distros/xenial/rules
debian/rules
packaging/el/inc/download_jmx_fetch

* Updates the URL to pull JMX jar from.

Update jmxfetch URL
